/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.FuncionarioController;
import javax.swing.JOptionPane;

/**
 *
 * @author luizf
 */
public class CadastroFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public CadastroFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtCargo = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        TxtSalarioBruto = new javax.swing.JTextField();
        TxtCpf = new javax.swing.JTextField();
        BtnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtsenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtCargo.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        TxtCargo.setOpaque(true);
        TxtCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCargoActionPerformed(evt);
            }
        });
        getContentPane().add(TxtCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 100, 22));

        txtNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNome.setOpaque(true);
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 100, 22));

        TxtSalarioBruto.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        TxtSalarioBruto.setOpaque(true);
        TxtSalarioBruto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSalarioBrutoActionPerformed(evt);
            }
        });
        getContentPane().add(TxtSalarioBruto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 100, 22));

        TxtCpf.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        TxtCpf.setOpaque(true);
        TxtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCpfActionPerformed(evt);
            }
        });
        getContentPane().add(TxtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 100, 22));

        BtnCancelar.setToolTipText("");
        BtnCancelar.setContentAreaFilled(false);
        BtnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 80, 20));

        btnSalvar.setToolTipText("");
        btnSalvar.setContentAreaFilled(false);
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 70, 20));

        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 30, 30));

        txtsenha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 100, 22));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resoucers/WhatsApp Image 2023-11-27 at 23.10.48.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 620, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
if(TxtCpf.getText().matches("")||txtsenha.getText().matches("")||txtNome.getText().matches("")||txtNome.getText().matches("")||TxtSalarioBruto.getText().matches("")||TxtCargo.getText().matches("")){
 JOptionPane.showMessageDialog(rootPane,"Preencha todos os campos");
    
}else{
        try{
    FuncionarioController funcionario = new FuncionarioController();
    funcionario.Cadastro(this);
}catch(Exception e){
    
}    
  }   
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TxtCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCargoActionPerformed

    private void TxtSalarioBrutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSalarioBrutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSalarioBrutoActionPerformed

    private void TxtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCpfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnCancelar;
    public javax.swing.JTextField TxtCargo;
    public javax.swing.JTextField TxtCpf;
    public javax.swing.JTextField TxtSalarioBruto;
    public javax.swing.JButton btnSalvar;
    public javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JTextField txtNome;
    public javax.swing.JPasswordField txtsenha;
    // End of variables declaration//GEN-END:variables

    public String insertFuncionario(String cpf, String nome, String cargo, String senha, Double salarioBruto) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
